apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhbGVqYW5kcm9zb2xmIiwicGFzc3dvcmQiOiJDYW1hcm85OC4iLCJlbWFpbCI6InNvbGlzX2FsZXg5OEBob3RtYWlsLmNvbSIsImF1dGgiOiJZV3hsYW1GdVpISnZjMjlzWmpwRFlXMWhjbTg1T0M0PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcreds
type: kubernetes.io/dockerconfigjson
