services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db

  application:
    image: alejandrosolf/asolis_application:latest
    container_name: application
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - BG_COLOR=teal
      - FAIL_FLAG=false
    depends_on:
      - mongo

volumes:
  mongo_data: